# Generated by Django 4.1.1 on 2022-09-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronic', '0002_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
